services:
  costimate-postgres-db:
    image: postgres:14.7
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - ./devdb:/var/lib/postgresql/data
    ports:
      - '6543:5432'
